### ISSUE TITLE
feat: add plugin concept

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-from-quill-delta#7]
Add ability for adopters to add custom resolvers for block and inline content types.

**Comment by bumi** [comment]
would this also allow to add support for custom blots? I am using [quill-mention](https://github.com/afry/quill-mention) and was wondering how this can be combined. 
I guess mentions could simply be text in mdast? 
Do you have a hint on what would need to be done to support this?

**Comment by ChristianMurphy** [comment]
> would this also allow to add support for custom blots?

Yes
That is exactly the kind of use case this would support.

> I guess mentions could simply be text in mdast?

To text, or if using extended syntax, a ping https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-ping#readme

> Do you have a hint on what would need to be done to support this?

1. support for nested block types like: https://github.com/syntax-tree/mdast-util-from-quill-delta/issues/5 and https://github.com/syntax-tree/mdast-util-from-quill-delta/issues/6 would need to be added.
 2. The logic for determining block types would need to be abstracted, something similar to https://github.com/remarkjs/remark/blob/121688c91c1e8aa6396518f62ee6dc4304d7b28c/packages/remark-stringify/lib/compiler.js#L37-L63
3. allow new block types to be added, and adding documentation on how to do so

Contributions are welcome!
