### ISSUE TITLE
test: investigate flakiness in coverage stats reporting

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-from-quill-delta#9]

**Comment by wooorm** [comment]
🤔 What’s up?

**Comment by wooorm** [comment]
GH looks to be having some problems? Weird!

**Comment by ChristianMurphy** [comment]
I've seen it intermittently locally as well.
Sometimes the coverage drops even without any code changes, then pops back up the next test run.

I suspect it has something to do with the ava or nyc preset.

**Comment by ChristianMurphy** [comment]
issue appears to be https://github.com/istanbuljs/nyc/issues/1148
